on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
    build-and-upload:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.build_branch }}
      - name: Install Python Deps
        run: |
          python -m pip install mako conan
      - name: Install Boost
        run: |
          conan profile detect --force
          conan install . --output-folder deps --build=missing
      - name: Configure ${{ inputs.name  }}
        run: |
          New-Item -Path build
          New-Item -Path install
          cmake -B build -S . -DBUILD_${{ inputs.name }}=ON -DCMAKE_INSTALL_PREFIX=install -DCMAKE_PREFIX_PATH=deps/generators
      - name: Build and Install ${{ inputs.name  }}
        run: |
         cmake --build build --target install
      - name: Checkout pages
        run: |
          git fetch --all
          git checkout -f -B pages --track origin/pages
      - name: Config Git User
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Actions from commit ${{ github.sha }}"
      - name: Create Artifact
        run: |
          7z a ${{ inputs.name }}-${{ inputs.version }}.tar -so install | 7z a -si ${{ inputs.name }}-${{ inputs.version }}.tar ${{ inputs.name }}-${{ inputs.version }}.tar.gz -mx1
      - name: Upload
        run: |
          git add ${{ inputs.name }}-${{ inputs.version }}.tar.gz
          git commit -m"Update ${{ inputs.name }}"
          git push -f
